# Generated by Django 4.0.3 on 2022-04-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
